version: "3.8"
services:
  aerospike:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    networks:
      - backend

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - aerospike
    environment:
      - AEROSPIC_HOST=aerospike
      - AEROSPIC_PORT=3000
    networks:
      - backend

networks:
  backend: