services:
  aerospike:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000:3000"
    ulimits:
      nofile:
        soft: 50000
        hard: 50000
    volumes:
      - ./aerospike.conf:/etc/aerospike/aerospike.conf

#  app:
#    build: .
#    depends_on:
#      - aerospike
#    environment:
#      - AEROSPIKE_HOST=aerospike
#      - AEROSPIKE_PORT=3000
#      - AEROSPIKE_NAMESPACE=test
#    restart: on-failure
#    volumes:
#      - .:/app/app